# base Dockerfile is at https://github.com/reynoldsnlp/view-tomcat
FROM reynoldsnlp/view-tomcat:latest

MAINTAINER Rob Reynolds <robert_reynolds@byu.edu>

COPY view /usr/local/tomcat/webapps/ROOT/

EXPOSE 8080
