module.exports = {
  PROVIDED_SOLUTION: "Solution was provided",
  EXACT_MATCH: "Perfect solution",
  LOWERCASE_MATCH: "Capitalization error",
  SPACE_MATCH: "Extra spaces",
  NO_DIAGNOSIS: "Unknown error",
  WRONG_LEMMA: "Word choice error in lemma",
  WRONG_POS: "Word choice error in part-of-speech",
  WRONG_CLICK: "Word choice error in click",
  WRONG_CLICK_BASIC: "Word choice error in click",
  WRONG_NUMBER: "Word form error in number",
  WRONG_CASE: "Word form error in case",
  WRONG_NUMBER_AND_CASE: "Word form error in number and case",
  WRONG_SPELLING: "Spelling error",
  WRONG_SPELLING_UNSTRESSED_O: "Spelling error in unstressed 'o' position",
  WRONG_SPELLING_UNSTRESSED_E: "Spelling error in unstressed 'e' position",
  NO_PALATALIZATION: "No soft-indicating letter after soft consonant",
  EXTRA_FLEETING_VOWEL: "Redundant fleeting vowel in the stem",
  MISSING_FLEETING_VOWEL: "Missing fleeting vowel in the stem"
};
