# VIEW assumes that this file is encoded in UTF-8, and will correctly read it if
# it contains UTF-8 multi-byte sequences

resources.base = WEB-INF/classes/models/

firebase.certificate = private/firebase-certificate.json
firebase.apiKey = my-firebase-api-key
firebase.authDomain = my-app-domain.firebaseapp.com
firebase.databaseURL = https://my-app-domain.firebaseio.com
firebase.storageBucket = my-app-domain.appspot.com
firebase.messagingSenderId = 1234

spacy.endpoint = https://spacy.aleks.bg/dep

# Use this if you want an in-memory data base.
# database.url = jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
database.url = jdbc:h2:./view.db
database.user = view
database.password = somePassword

template.cache = false
template.precompile = false

lingpipe.tagger.en = lgptagger/pos-en-general-brown.HiddenMarkovModel

opennlp.tokenizer.en  = opennlp-1.5/en-token.bin
opennlp.tokenizer.de  = opennlp-1.5/en-token.bin
opennlp.tokenizer.es  = opennlp-1.5/en-token.bin
opennlp.tokenizer.ru  = opennlp-1.5/ru-token.bin
#opennlp.tokenizer.de  = opennlp/models-1.4/german/tokenize/tokenModel.bin.gz
#opennlp.tokenizer.es  = opennlp/models-1.4/spanish/tokenize/SpanishTok.bin.gz

opennlp.sbd.en = opennlp-1.5/en-sent.bin
opennlp.sbd.de = opennlp-1.5/en-sent.bin
opennlp.sbd.es = opennlp-1.5/en-sent.bin
opennlp.sbd.ru = opennlp-1.5/ru-sent.bin
#opennlp.sbd.de = opennlp/models-1.4/german/sentdetect/sentenceModel.bin.gz
#opennlp.sbd.es = opennlp/models-1.4/spanish/sentdetect/SpanishSent.bin.gz

opennlp.tagger.en = opennlp-1.5/en-pos-maxent.bin
opennlp.tagger.de = opennlp-1.5/en-pos-maxent.bin
opennlp.tagger.es = opennlp-1.5/en-pos-maxent.bin
#opennlp.tagger.de = opennlp/models-1.4/german/postag/posModel.bin.gz
#opennlp.tagger.es = opennlp/models-1.4/spanish/postag/SpanishPOS.bin.gz

opennlp.tagger.dictionary.en = opennlp/models-1.4/english/postag/tagdict

stanfordP.en = edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz
maltparser.en = ptb2.engmaltdefaults.linear.nomergefeatures
onlpchunker.en        = opennlp/models-1.4/english/chunker/EnglishChunk.bin.gz
#onlpchunker.es        = opennlp/models-1.4/spanish/chunker/SpanishTokChunk.bin.gz

morphg.binary = /usr/local/bin/morphg
morphg.verbstemList = /usr/local/werti/resources/verbstem.list

hfst.analyser.ru        = hfst/ru-analyser-gt-desc.hfstol
hfst.analyser-mal.ru  = hfst/ru-analyser-gt-desc-mal.hfstol
hfst.generator.ru       = hfst/ru-generator-gt-desc.hfstol
hfst.stressgenerator.ru = hfst/ru-generator-gt-desc.accented.hfstol
hfst.phoneticgenerator.ru = hfst/ru-generator-gt-desc.phonetic.hfstol
hfst.g2p.ru = hfst/ru-g2p.hfstol

hfst.analyser.et        = hfst/et-analyser-gt-desc.hfstol
hfst.generator.et       = hfst/et-generator-gt-desc.hfstol

kryo.imperfectiveToPerfectiveVerbMap.ru = enhancer-resources/imperfectiveToPerfectiveVerbMap.ser
kryo.lemmaToExemplarMap.ru = enhancer-resources/lemmaToExemplarMap.ser
kryo.lemmaToTranslationsMap.ru = enhancer-resources/lemmaToTranslationsMap.ser
kryo.perfectiveToImperfectiveVerbMap.ru = enhancer-resources/perfectiveToImperfectiveVerbMap.ser
kryo.lemmaToTranslationsMapWiktExtract.ru = enhancer-resources/lemmaToTranslationsMapWiktExtract.ser

participles.adjectivesToExcludeFromParticiples.ru = enhancer-resources/adjectivesToExcludeFromParticiples.txt

visl.cg-conv.binary = /usr/local/bin/cg-conv
visl.cg3.binary = /usr/local/bin/vislcg3
visl.cg3.grammar.ru = vislcg3/ru-disambiguation.cg3
visl.cg3.grammar.et = vislcg3/et-disambiguation.cg3

treetagger-model.es = treetagger/spanish-par-linux-3.2-utf8.bin
treetagger-encoding.es = utf8

treetagger-model.de = treetagger/german-par-linux-3.2-utf8.bin
treetagger-encoding.de = utf8

rftagger.de = rftagger/german-pc-64bit.par

stanfordP.de = edu/stanford/nlp/models/lexparser/germanPCFG.ser.gz
maltparser.de = tuebadz6-nocyclesents-maltopt

htmlcontent.misc = html-content/model.bin
htmlsmoother.misc = html-content/smoother.bin

descriptorPath = WEB-INF/classes/

post.pos = enhancers/PoSEnhancer.xml
post.ask = enhancers/TokenEnhancer.xml
post.conditional = enhancers/ConditionalEnhancer.xml

pre.tagger = operators/Lingpipe.xml
pre.conditional = testers/ConditionalTester.xml

post.gerunds = operators/vislCGPostProc.xml
pre.gerunds = operators/vislcg3Pipe.xml
